### ISSUE TITLE
Working examples?

### ISSUE THREAD

**Issue by wicast** [LucentFlux/include-wgsl-oil#1]
I tried following README to setup a project , bug only get error: `expected Fn, Struct, Var, Let, Const, Alias or Override, but found Ident
` on the include line.
Need some help, thx

**Comment by uki-dev** [comment]
Also struggling to get includes working.

**Comment by Joeoc2001** [comment]
Thanks for your interest in this crate! 

So far I've just been adding features as I needed them in my project, but if there's interest in using this library in other projects then it makes sense for me to spend the next few days improving documentation and error messages. Hopefully it'll be easier to start using after then.

**Comment by Joeoc2001** [comment]
I've spent some time improving error messages, import resolution logic and documentation - there's now 3 working examples and I've fixed the 'getting started' snippet. Let me know if you're still having any issues getting started and if you are, what you're trying, so that I know what to document further :)
